---
{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{  .Chart.Name }}-pdb"
  namespace: {{.Values.appNamespace}}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{  .Chart.Name }}-selector"
{{- end }}
